#!/bin/bash 

      project=ts_warm_bore # $1 # ts_warm_bore

         dsid=$1 # 711_0001
  input_stage=$2 # s1
input_dataset=$3
    job_stage=$4  # s1 s2 s3
      jobtype=$4  # sim ... stn
        jobid=$5
         doit=$6

prefix="echo " ; if [ ".$doit" != "." ] ; then prefix="" ; fi

topdir=/pnfs/mu2e/scratch/users/murat/workflow/${project}.${dsid}.${input_stage}_${input_dataset}.${jobtype}/outstage/$jobid


#------------------------------------------------------------------------------
# 1. copy log files
#------------------------------------------------------------------------------
outputdir=/mu2e/data/users/murat/datasets/$project/$dsid/$iob_stage/log
if [ ! -d $outputdir ] ; then mkdir -p $outputdir ; fi

for f in `ls $topdir/*/*/*.log*` ; do 
    ${prefix}cp $f $outputdir/.
done
