#!/bin/bash 

      project=ts_warm_bore # $1 # ts_warm_bore

         dsid=$1 # 711_0001
  input_stage=$2 # s1
input_dataset=$3
    job_stage=$4  # s1 s2 s3
      jobtype=$5  # sim ... stn
        jobid=$6
         doit=$7

prefix="echo " ; if [ ".$doit" != "." ] ; then prefix="" ; fi

topdir=/pnfs/mu2e/scratch/users/murat/workflow/${project}.${dsid}.${input_stage}_${input_dataset}.${job_stage}/outstage/$jobid

#------------------------------------------------------------------------------
# 1. copy log files and print number of events in output streams
#------------------------------------------------------------------------------
outputdir=/mu2e/data/users/murat/datasets/$project/$dsid/$job_stage/log
if [ ! -d $outputdir ] ; then  ${prefix}mkdir -p $outputdir ; fi

for f in `ls $topdir/*/*/log.*.log` ; do 
    ${prefix}cp $f $outputdir/.
done
#------------------------------------------------------------------------------
# check if the jobs finished successfully
#------------------------------------------------------------------------------
for f in `ls $outputdir/*.log` ; do 
    x=`cat $f | grep "mu2egrid exit status" | awk '{print $4}'` ; 
    if [ .$x != ."0" ] ; then 
	echo $f: ERROR ; 
    fi; 
done

if   [ $job_stage == "s3" ] ; then output_streams="mothers crv tgtstop ootstop truncated"
elif [ $job_stage == "s1" ] ; then output_streams="mubeam truncated dsregion extmonbeam extmonregion"
elif [ $job_stage == "s2" ] ; then output_streams="mubeam truncated crv"
fi

for stream in $output_streams ; do
    cat $outputdir/*.log | grep TrigReport | grep -i $stream | awk -v s=$stream '{n+=$5} END{printf "stream=%-10s nevents=%10i\n",s,n}'
done
