#!/bin/bash 

      project=$1  # ts_warm_bore
         dsid=$2  # 711_0001
       istage=$3  # gen, .... s1
      istream=$4  # mubeam or 250_20000
     job_type=$5  # s1_sim s2_sim s3_sim
         doit=$6

prefix="echo " ; if [ ".$doit" != "." ] ; then prefix="" ; fi

aaa_project_file=$project/AAA_PROJECT.txt
      grid_jobid=`cat $aaa_project_file | grep $dsid | grep $istage | awk -v istage=$istage '{if ($2 == istage) print $10}'`
       job_stage=`echo $job_type | awk -F _ '{print $1}'`

topdir=/pnfs/mu2e/scratch/users/murat/workflow/${project}.${dsid}.${istage}_${istream}.${job_type}/outstage/$grid_jobid
echo topdir=$topdir
#------------------------------------------------------------------------------
# 1. copy log files and print number of events in output streams
#------------------------------------------------------------------------------
outputdir=/mu2e/data/users/murat/datasets/$project/$dsid/$job_stage/log
echo outputdir=$outputdir
# exit

if [ ! -d $outputdir ] ; then mkdir -p $outputdir ; fi

for f in `ls $topdir/*/*/log.*.log` ; do 
    cp $f $outputdir/.
done
#------------------------------------------------------------------------------
# check if the jobs finished successfully
#------------------------------------------------------------------------------
for f in `ls $outputdir/*.log` ; do 
    x=`cat $f | grep "mu2egrid exit status" | awk '{print $4}'` ; 
    if [ .$x != ."0" ] ; then 
	echo $f: ERROR ; 
    fi; 
done

if   [ $job_type == "s3_sim" ] ; then output_streams="mothers crv tgtstop ootstop truncated"
elif [ $job_type == "s1_sim" ] ; then output_streams="mubeam truncated dsregion extmonbeam extmonregion"
elif [ $job_type == "s2_sim" ] ; then output_streams="mubeam truncated crv"
fi

for stream in $output_streams ; do
    cat $outputdir/*.log | grep TrigReport | grep -i $stream | awk -v s=$stream '{n+=$5} END{printf "stream=%-10s nevents=%10i\n",s,n}'
done
