#!/bin/bash
# probably, can source

     project=$1 # ts_warm_bore
        dsid=$2 # 711_1010

#  input_stage=$3 # s1
# input_stream=$4 # gen
# output_stage=$5 # s2
#     job_type=$6 # sim , stn
#        jobid=$7 # 17161389
# 

# step 1: check grid output

nev_per_segment=`cat ts_warm_bore/AAA_PROJECT.txt | grep $dsid | grep s1 | awk '{print $6}'`
      nsegments=`cat ts_warm_bore/AAA_PROJECT.txt | grep $dsid | grep s1 | awk '{print $7}'`

echo $nev_per_segment  $nsegments

aaa_project_file=$project/AAA_PROJECT.txt
            odir=/grid/fermiapp/mu2e/users/murat/catalogs/$project/$dsid/s1
         logfile=$odir/$project.${dsid}.gen_250_20000_s1_sim.check_grid_output.log

if [ ! -d $odir ] ; then mkdir -p $odir ; fi
$project/scripts/check_grid_output $project $dsid gen 500_20000 s1_sim  >| $logfile

$project/scripts/copy_log_files    $project $dsid gen 500_20000 s1_sim  .

$project/scripts/list_pnfs_files   $project $dsid gen 500_20000 s1_sim mubeam .

$project/scripts/gen_fcl           $project $dsid s1  mubeam    s2_sim .

# for pbars, use 15h and ifdh
$project/scripts/submit_grid_job   $project $dsid s1  mubeam    s2_sim 8h xrootd .
