#!/bin/bash
# probably, can source

     project=$1 # ts_warm_bore
        dsid=$2 # 711_1010
      istage=$3 # gen
     istream=$4 # 500_20000
    job_type=$5 # s1_sim

 ostage=`echo $job_type | awk -F _ '{print $1}'`
jobtype=`echo $job_type | awk -F _ '{print $2}'`


   odir=/mu2e/data/users/murat/subprojects/$project/catalogs/$dsid/s2
logfile=$odir/$project.${dsid}.${istage}_${istream}_${job_type}.check_grid_output.log

$project/scripts/check_grid_output $project $dsid $istage $istream $job_type >| $logfile

$project/scripts/copy_log_files    $project $dsid $istage $istream $job_type  .

$project/scripts/list_pnfs_files   $project $dsid $istage $istream $job_type mubeam    .
$project/scripts/list_pnfs_files   $project $dsid $istage $istream $job_type crv       .
$project/scripts/list_pnfs_files   $project $dsid $istage $istream $job_type truncated .

$project/scripts/gen_fcl           $project $dsid s2  mubeam  s3_sim .

$project/scripts/submit_grid_job   $project $dsid s2  mubeam  s3_sim .
