#!/bin/bash
# probably, can source

      project=$1 ; echo project:$project   # ts_warm_bore
         dsid=$2 ; echo dsid:$dsid  # 711_1011
  input_stage=$3 ; echo input_stage:$input_stage   # s1
 input_stream=$4 ; echo input_stream:$input_stream   # mubeam
     job_type=$5 ; echo job_type:$job_type   # sim , stn
 output_stage=$6 ; echo output_stage:$output_stage   # s2
output_stream=$7 ; echo output_stream:$output_stream   # mubeam
        jobid=$8 ; echo jobid:$jobid  

# step 1: check grid output

nev_per_segment=`cat ts_warm_bore/AAA_PROJECT.txt | grep $dsid | grep s1 | awk '{print $6}'`
      nsegments=`cat ts_warm_bore/AAA_PROJECT.txt | grep $dsid | grep s1 | awk '{print $7}'`

echo $nev_per_segment  $nsegments

check_grid_output_log=/grid/fermiapp/mu2e/users/murat/catalogs/$project/$dsid/s2/$project.${dsid}_s2.check_grid_output.log
murat/scripts/check_grid_output  $project.$dsid.${input_stage}_${input_stream}.${output_stage} $jobid >| $check_grid_output_log
 
ts_warm_bore/scripts/copy_log_files              $dsid $input_stage $input_stream $output_stage $job_type $jobid  .

                pnfs_dir=/pnfs/mu2e/scratch/users/murat/workflow/$project.$dsid.${input_stage}_${input_stream}.$output_stage/outstage/$jobid
output_stream_file_list=/grid/fermiapp/mu2e/users/murat/catalogs/$project/$dsid/$output_stage/$project.${dsid}_${output_stage}.$output_stream.art

echo pnfs_dir:$pnfs_dir
echo output_stream_file_list:$output_stream_file_list

ls $pnfs_dir/00/*/*.art | grep TS-mubeam | grep -v json >| $output_stream_file_list

$project/scripts/gen_fcl         $project $dsid $output_stage $output_stream s3 sim .
$project/scripts/submit_grid_job $project $dsid $output_stage $output_stream s3 sim .

