#!/bin/bash 

      project=ts_warm_bore # this one is fixed
         dsid=$1 # 711_0001
  input_stage=$2 # gen
 input_stream=$3 # 250_20000
 output_stage=$4 # s2
   output_job=$5
output_stream=$6 # mubeam
        jobid=$7
         doit=$7


prefix="echo executing: "
if [ ".$doit" != "." ] ; then prefix="" ; fi

topdir=/pnfs/mu2e/scratch/users/murat/workflow/${project}.${dsid}.${input_stage}_${input_stream}.${output_stage}_$output_job/outstage/$jobid
echo topdir=$topdir

outputdir=$CATALOG_DIR/$project/$dsid/$output_stage
if [ ! -d $outputdir ] ; then mkdir -p $outputdir ; fi
echo outputdir=$outputdir
#------------------------------------------------------------------------------
# catalog - so far, only .art files
#------------------------------------------------------------------------------
catalog_fn=$outputdir/$project.${dsid}.${output_stage}_$output_stream.art.files
echo catalog_fn=$catalog_fn

if [ -f $catalog_fn ] ; then 
    echo $catalog_fn already exists, BAIL OUT
    exit -1
fi

${prefix}touch $catalog_fn

echo list dir="$topdir/*/*/*"

# ls $topdir/*/*/*.art

for f in `ls $topdir/*/*/*.art` ; do
    base=`basename $f` ;
    os=`echo $base | awk -F . '{print $3}'`
#    echo base=$base os=$os
    if [ ."`echo $os | grep -i $output_stream`" != "." ] ; then
#	echo os=$os output_stream=$output_stream  adding file to catalog
	echo $f >> $catalog_fn
    fi
done

${prefix}cat $catalog_fn 

if [ ".$doit" != "." ] ; then 
    nfiles=`cat $catalog_fn | wc -l`
    echo nfiles = $nfiles
fi
