#!/bin/bash 

project=ts_warm_bore # $1 # ts_inner_bore
   dsid=$1 # 711_0001
  stage=$2
  jobid=$3
 stream=$4
   doit=$5


prefix="echo "
if [ ".$doit" != "." ] ; then prefix="" ; fi

topdir=/pnfs/mu2e/scratch/users/murat/workflow/${project}.${dsid}_${stage}/outstage/$jobid
outputdir=$CATALOG_DIR/$project/$dsid/$stage
if [ ! -d $outputdir ] ; then mkdir -p $outputdir ; fi
echo outputdir=$outputdir
#------------------------------------------------------------------------------
# catalog - so far, only .art files
#------------------------------------------------------------------------------
catalog_fn=$project.${dsid}_${stage}.$stream.art
echo topdir=$topdir

${prefix}ls  $topdir/*/*/*.art | grep -i $stream >| $outputdir/$catalog_fn

${prefix}cat $outputdir/$catalog_fn 

if [ ".$doit" != "." ] ; then 
    nfiles=`cat $outputdir/$catalog_fn | wc -l`
    echo nfiles = $nfiles
fi
