#!/usr/bin/bash

project=$1 # ts_warm_bore
   dsid=$2 # 711_0001
 istage=$3 # gen_250_20000
 ostage=$3 # s1_sim
  jobid=$4 # 
   doit=$5
  
  if [ ".$doit" == "." ] ; then prefix="echo "; else prefix="" ; fi

 input_dir=/pnfs/mu2e/scratch/users/murat/workflow/$project.$dsid.$istage.$ostage/outstage/$jobid
output_dir=/mu2e/data/users/murat/datasets/$project/$dsid/$stage

for stream in crv mubeam truncated ; do
    for f in $input_dir/00/*/sim.murat.TS-$stream.*.art ; do 
	${prefix} cp $f $output_dir/$stream/.  
    done
done

for f in $input_dir/00/*/nts.murat.*.root ; do 
    ${prefix} cp $f $output_dir/hist/. 
done

for f in $input_dir/00/*/log.*.log ; do 
    ${prefix} cp $f $output_dir/log/.  
done
