#!/bin/bash 
#------------------------------------------------------------------------------
# one thing for sure: for different projects the grid submission is slightly different
# - the code tarball naming may follow different rules
# by default, use dcache
#------------------------------------------------------------------------------
        project=$1 # ts_warm_bore
         p_dsid=$2 # 711_0001
            ist=$3 # s1:mubeam[:01] ... or gen:250_20000 ; if 'gen', '250_20000' means 'njobs_neventsPerJob'
       job_type=$4 # 's1_sim' or 's1_stn' , for example
           time=$5 # 
	 xrootd=$6 #
           doit=$7 # "." or "ifdh"


        dsid=`echo $p_dsid | awk -F : '{print $1}'`
        fclt=`echo $p_dsid | awk -F : '{print $2}'`

 input_stage=`echo $ist | awk -F : '{print $1}'`;
input_stream=`echo $ist | awk -F : '{print $2}'`;
     fileset=`echo $ist | awk -F : '{print $3}'`;

  input_stub=`echo $ist | sed 's/:/_/g'`;

prefix='echo ' ; if [ ".$doit" != "." ] ; then prefix='' ; fi

expected_job_time=8h
if [ $time != "." ] ; then expected_job_time=$time ; fi

setup mu2etools
setup mu2efiletools
setup mu2egrid 

dsconf=${dsid}_${input_stub}

code_tarball=/pnfs/mu2e/resilient/users/murat/$project.code.tbz

 fcl_tarball=/pnfs/mu2e/resilient/users/murat/$project.$dsid.$input_stub.$job_type.fcl.tbz
if [ ".$fclt" != "." ] ; then fcl_tarball=$fclt ; fi

dataset_conf=${project}_${dsid}_${input_stub}_$job_type
work_project=${project}.${dsid}.${input_stub}.$job_type

parameters="--code=$code_tarball --fcllist=$fcl_tarball  --dsconf=$dataset_conf  --wfproject=$work_project  --expected-lifetime=$time"
if [ $xrootd == "xrootd" ] ; then parameters=$parameters" --xrootd" ; fi

$prefix mu2eprodsys $parameters
